# docker-compose.yml
version: "3.8"

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tron_db
    volumes:
      - tron_db_data:/var/lib/postgresql/data
    networks:
      - tron_network
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://user:password@db/tron_db
    networks:
      - tron_network

volumes:
  tron_db_data:

networks:
  tron_network:
    driver: bridge
